credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: "$2b$12$f2FZjfa3XA0BqkD0BBg5huoLAV1k087Rx1Vr8P7MgpsneoArnPRpu"

cookie:
  expiry_days: 30
  key: "ThisIsA32CharacterLongSecureKeyForCookies123"
  name: "tariff_app_cookie"

preauthorized:
  emails: []